# Site settings
title: Real Jays Blog
email: realjays1204@gmail.com
description: "jays blog. 매일 매일 무언가 잡지식이라도 쓰는 것을 목표로 함."
baseurl: ""
url: "http://jays1204.github.io"
twitter_username: jays1204
github_username:  jays1204
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]

highlighter: pygments
# Build settings
permalink: pretty
