# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Real Jays Blog
email: realjays1204@gmail.com
description: "jays blog. 매일 매일 무언가 잡지식이라도 쓰는 것을 목표로 함."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jays1204.github.io" # the base hostname & protocol for your site
github_username:  jays1204
github: jays1204

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
